### ISSUE TITLE
does not compile - syntax error ru.po

### ISSUE THREAD

**Issue by FalcoGer** [StefanoDeVuono/steghide#11]
When compiling with `./configure && make` it generates this error.

```
Making all in po
make[2]: Entering directory '/home/paul/repositories/steghide/po'
cd .. \
  && CONFIG_FILES=po/Makefile.in CONFIG_HEADERS= \
       /bin/sh ./config.status
config.status: creating po/Makefile.in
config.status: WARNING:  'po/Makefile.in.in' seems to ignore the --datarootdir setting
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
rm -f de.gmo && /usr/bin/msgfmt -c --statistics -o de.gmo de.po
rm -f fr.gmo && /usr/bin/msgfmt -c --statistics -o fr.gmo fr.po
rm -f ro.gmo && /usr/bin/msgfmt -c --statistics -o ro.gmo ro.po
rm -f es.gmo && /usr/bin/msgfmt -c --statistics -o es.gmo es.po
de.po:7: warning: header field 'Language' missing in header
185 translated messages.
ro.po:6: warning: header field 'Language' missing in header
185 translated messages.
es.po:6: warning: fr.po:8: warning: header field 'Language' missing in header
header field 'Language' missing in header
185 translated messages.
185 translated messages.
rm -f ru.gmo && /usr/bin/msgfmt -c --statistics -o ru.gmo ru.po
ru.po:1219:10: syntax error
/usr/bin/msgfmt: found 1 fatal error
make[2]: *** [Makefile:207: ru.gmo] Error 1
make[2]: Leaving directory '/home/paul/repositories/steghide/po'
make[1]: *** [Makefile:259: all-recursive] Error 1
make[1]: Leaving directory '/home/paul/repositories/steghide'
make: *** [Makefile:190: all] Error 2
```

I don't need russian text, so i removed ru.po and all related files from the makefile in po.
I get the following output.

```
[...]
In file included from common.h:101,
                 from MCryptPP.h:21,
                 from Arguments.cc:25:
Arguments.h:103:22: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float Arguments::Default_Goal’ of non-integral type [-fpermissive]
  103 |  static const float  Default_Goal = 100.0 ;
      |                      ^~~~~~~~~~~~
[...]
In file included from AuFile.cc:26:
AuData.h:29:13: error: specializing member ‘AudioDataImpl<AuMuLaw, unsigned char>::readValue’ requires ‘template<>’ syntax
   29 | inline BYTE AuMuLawAudioData::readValue (BinaryIO* io) const { return (io->read8()) ; }
      |             ^~~~~~~~~~~~~~~~
AuData.h:30:13: error: specializing member ‘AudioDataImpl<AuMuLaw, unsigned char>::writeValue’ requires ‘template<>’ syntax
   30 | inline void AuMuLawAudioData::writeValue (BinaryIO* io, BYTE v) const { io->write8(v) ; }
      |             ^~~~~~~~~~~~~~~~
AuData.h:34:14: error: specializing member ‘AudioDataImpl<AuPCM8, signed char>::readValue’ requires ‘template<>’ syntax
   34 | inline SBYTE AuPCM8AudioData::readValue (BinaryIO* io) const { return ((SBYTE) io->read8()) ; }
      |              ^~~~~~~~~~~~~~~
AuData.h:35:13: error: specializing member ‘AudioDataImpl<AuPCM8, signed char>::writeValue’ requires ‘template<>’ syntax
   35 | inline void AuPCM8AudioData::writeValue (BinaryIO* io, SBYTE v) const { io->write8((BYTE) v) ; }
      |             ^~~~~~~~~~~~~~~
AuData.h:39:16: error: specializing member ‘AudioDataImpl<AuPCM16, short int>::readValue’ requires ‘template<>’ syntax
   39 | inline SWORD16 AuPCM16AudioData::readValue (BinaryIO* io) const { return ((SWORD16) io->read16_be()) ; }
      |                ^~~~~~~~~~~~~~~~
AuData.h:40:13: error: specializing member ‘AudioDataImpl<AuPCM16, short int>::writeValue’ requires ‘template<>’ syntax
   40 | inline void AuPCM16AudioData::writeValue (BinaryIO* io, SWORD16 v) const { io->write16_be((UWORD16) v) ; }
      |             ^~~~~~~~~~~~~~~~
AuData.h:44:16: error: specializing member ‘AudioDataImpl<AuPCM32, int>::readValue’ requires ‘template<>’ syntax
   44 | inline SWORD32 AuPCM32AudioData::readValue (BinaryIO* io) const { return ((SWORD32) io->read32_be()) ; }
      |                ^~~~~~~~~~~~~~~~
AuData.h:45:13: error: specializing member ‘AudioDataImpl<AuPCM32, int>::writeValue’ requires ‘template<>’ syntax
   45 | inline void AuPCM32AudioData::writeValue (BinaryIO* io, SWORD32 v) const { io->write32_be((UWORD32) v) ; }
      |             ^~~~~~~~~~~~~~~~

```

**Comment by telometto** [comment]
I'm experiencing the same issue. Bumping.

**Comment by Osiris9999** [comment]
I'm experiencing the same issue here

**Comment by Aminuxer** [comment]
I try to make without ru-translation (delete ru.ro + remove str ru from LINGUAS), but catch same error.
I fix old translation issue in this commit: https://github.com/StefanoDeVuono/steghide/commit/f418955c40419ac39d7595f291e28c18d750dccb
and this commit has been merged.

After re-enable ru-translation, i catch accurate same error when making in src direcory, not in doc / po :

...
Making all in po
make[2]: Entering directory '/home/test/steghide/steghide-master/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/test/steghide/steghide-master/po'
...
Making all in doc
make[2]: Entering directory '/home/test/steghide/steghide-master/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/test/steghide/steghide-master/doc'
....
Making all in src
make[2]: Entering directory '/home/test/steghide/steghide-master/src'
if g++ -DHAVE_CONFIG_H -I. -I. -I..  -DLOCALEDIR=\"/usr/local/share/locale\"   -O2 -Wall -MT Arg.o -MD -MP -MF ".deps/Arg.Tpo" \
  -c -o Arg.o `test -f 'Arg.cc' || echo './'`Arg.cc; \
then mv ".deps/Arg.Tpo" ".deps/Arg.Po"; \
else rm -f ".deps/Arg.Tpo"; exit 1; \
fi
if g++ -DHAVE_CONFIG_H -I. -I. -I..  -DLOCALEDIR=\"/usr/local/share/locale\"   -O2 -Wall -MT Arguments.o -MD -MP -MF ".deps/Arguments.Tpo" \
  -c -o Arguments.o `test -f 'Arguments.cc' || echo './'`Arguments.cc; \
then mv ".deps/Arguments.Tpo" ".deps/Arguments.Po"; \
else rm -f ".deps/Arguments.Tpo"; exit 1; \
fi
In file included from common.h:101,
                 from MCryptPP.h:21,
                 from Arguments.cc:25:
Arguments.h:103:41: error: 'constexpr' needed for in-class initialization of static data member 'const float Arguments::Default_Goal' of non-integral type [-fpermissive]
  103 |         static const float              Default_Goal = 100.0 ;
      |                                         ^~~~~~~~~~~~
make[2]: *** [Makefile:395: Arguments.o] Error 1
make[2]: Leaving directory '/home/test/steghide/steghide-master/src'
make[1]: *** [Makefile:259: all-recursive] Error 1
make[1]: Leaving directory '/home/test/steghide/steghide-master'
make: *** [Makefile:190: all] Error 2

OS : Fedora 36, packagesd  libjpeg-turbo-devel, libmcrypt-devel, mhash-devel , gcc, g++ was previously installed.

**Comment by nick863** [comment]
It seems like a problem is related to C++ notation. The Arguments.h error may be solved by setting
```export CPPFLAGS="-std=c++98"```
But then it will result in another issues related to in-line declaration of  methods for template classes. I think, there is a flag which switches g++ to old behavior.

I have created the patch to allow compiling on modern versions of g++. I was able to compile steghide, all tests has passed and I also did sanity check myself. I also would be happy to create pull request with fix, but I do not have the permission.
**NOTE:** During compiling some localization files were changed. These changes are also included tnto the patch, though it is not importaint, it seems there is a linter step somewhere.

PS: Thank you for developing the great product!

`diff --git a/README b/README
index f8fe6ac..323bda1 100644
--- a/README
+++ b/README
@@ -68,6 +68,13 @@ After unpacking the source distribution, enter the following commands:
 3) make check
 4) make install (as root)
 
+Note: Before running unit tests with "make check" please add tests folder to
+perl @INC as follows.
+on Linux/Unix systems:
+export PERL5LIB=/path/to/repository/steghide/tests
+On Windows:
+set PERL5LIB=C:\path\to\repository\steghide\tests
+
 For more information see the generic installation instructions in the file
 INSTALL that came with the distribution.
 
diff --git a/po/de.po b/po/de.po
index c5a71ae..b3d3092 100644
--- a/po/de.po
+++ b/po/de.po
@@ -10,6 +10,7 @@ msgstr ""
 "PO-Revision-Date: 2003-09-29 14:09+0200\n"
 "Last-Translator: Stefan Hetzl <shetzl@chello.at>\n"
 "Language-Team: Deutsch\n"
+"Language: \n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=ISO-8859-1\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -488,8 +489,8 @@ msgstr ""
 msgid ""
 "the bmp file \"%s\" has a format that is not supported (bcBitCount: %d)."
 msgstr ""
-"Die bmp-Datei \"%s\" hat ein Format das nicht unterstützt wird (bcBitCount: %"
-"d)."
+"Die bmp-Datei \"%s\" hat ein Format das nicht unterstützt wird (bcBitCount: "
+"%d)."
 
 #: src/BmpFile.cc:669
 #, c-format
diff --git a/po/es.po b/po/es.po
index 7e145c4..adf35e6 100644
--- a/po/es.po
+++ b/po/es.po
@@ -9,6 +9,7 @@ msgstr ""
 "PO-Revision-Date: 2003-10-05 16:28-0300\n"
 "Last-Translator: Alberto A. Schiano <chanio@users.sourceforge.net>\n"
 "Language-Team: spanish\n"
+"Language: \n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=ISO-8859-1\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -412,8 +413,8 @@ msgid ""
 "the bmp data from standard input has a format that is not supported "
 "(biBitCount: %d)."
 msgstr ""
-"el archivo bmp de la entrada estandar tiene un formato que no reconozco"
-"(biBitCount: %d)."
+"el archivo bmp de la entrada estandar tiene un formato que no "
+"reconozco(biBitCount: %d)."
 
 #: src/BmpFile.cc:495
 #, c-format
@@ -952,8 +953,8 @@ msgstr ""
 #, c-format
 msgid "an error occured while writing the wav headers to the file \"%s\"."
 msgstr ""
-"ocurrió un error mientras se escribian las cabeceras wav en el archivo \"%s"
-"\"."
+"ocurrió un error mientras se escribian las cabeceras wav en el archivo "
+"\"%s\"."
 
 #: src/WavFile.cc:400
 msgid "an error occured while writing the wav headers to standard output."
diff --git a/po/fr.po b/po/fr.po
index 7a10c30..d92ce5d 100644
--- a/po/fr.po
+++ b/po/fr.po
@@ -11,6 +11,7 @@ msgstr ""
 "PO-Revision-Date: 2003-09-29 14:09+0200\n"
 "Last-Translator: Stefan Hetzl <shetzl@chello.at>\n"
 "Language-Team: Deutsch\n"
+"Language: \n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=ISO-8859-1\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -91,8 +92,8 @@ msgstr "l'argument \"%s\" doit 
 msgid ""
 "the argument \"%s\" can only be used with the \"%s\" and \"%s\" commands."
 msgstr ""
-"le paramètre \"%s\" ne peut être utilisé qu'avec les commandes \"%s\" and \"%"
-"s\"."
+"le paramètre \"%s\" ne peut être utilisé qu'avec les commandes \"%s\" and "
+"\"%s\"."
 
 #: src/Arguments.cc:306
 #, c-format
@@ -293,8 +294,8 @@ msgstr ""
 #, c-format
 msgid "an error occured while writing the au headers to the file \"%s\"."
 msgstr ""
-"une erreur a eu lieu lors de l'écriture de l'entête au vers le fichier \"%s"
-"\"."
+"une erreur a eu lieu lors de l'écriture de l'entête au vers le fichier "
+"\"%s\"."
 
 #: src/AuFile.cc:171
 msgid "an error occured while writing the au headers to standard output."
@@ -343,8 +344,8 @@ msgstr ""
 #, c-format
 msgid "an error occured while writing the audio data to the file \"%s\"."
 msgstr ""
-"une erreur a eu lieu lors de l'écriture des données audio vers le fichier \"%"
-"s\"."
+"une erreur a eu lieu lors de l'écriture des données audio vers le fichier "
+"\"%s\"."
 
 #: src/AudioData.h:140 src/WavFile.cc:306
 msgid "an error occured while writing the audio data to standard output."
@@ -501,8 +502,8 @@ msgstr "le fichier \"%s\" a un format qui n'est pas support
 #, c-format
 msgid "an error occured while writing the bmp headers to the file \"%s\"."
 msgstr ""
-"une erreur a eu lieu lors de l'écriture de l'entête bmp vers le fichier \"%s"
-"\"."
+"une erreur a eu lieu lors de l'écriture de l'entête bmp vers le fichier "
+"\"%s\"."
 
 #: src/BmpFile.cc:673
 msgid "an error occured while writing the bmp headers to standard output."
@@ -1003,8 +1004,8 @@ msgstr ""
 #, c-format
 msgid "an error occured while writing the wav headers to the file \"%s\"."
 msgstr ""
-"une erreur a eu lieu lors de l'écriture de l'entête wav vers le fichier \"%s"
-"\"."
+"une erreur a eu lieu lors de l'écriture de l'entête wav vers le fichier "
+"\"%s\"."
 
 #: src/WavFile.cc:400
 msgid "an error occured while writing the wav headers to standard output."
@@ -1072,8 +1073,8 @@ msgstr ""
 #, c-format
 msgid "an error occured while reading data from the file \"%s\"."
 msgstr ""
-"une erreur a eu lieu lors de la lecture des données à partir du fichier \"%s"
-"\"."
+"une erreur a eu lieu lors de la lecture des données à partir du fichier "
+"\"%s\"."
 
 #: src/error.cc:93
 msgid "an error occured while writing data to standard output."
@@ -1185,8 +1186,8 @@ msgstr "terminal inconnu. Vous devez appuyer sur <Entr
 #, fuzzy
 #~ msgid "the \"%s\" argument must be followed by the plain file name."
 #~ msgstr ""
-#~ "l'argument \"%s\" doit être suivi du nom du fichier de données. tapez \"%"
-#~ "s --help\" pour l'aide."
+#~ "l'argument \"%s\" doit être suivi du nom du fichier de données. tapez "
+#~ "\"%s --help\" pour l'aide."
 
 #, fuzzy
 #~ msgid "the stego file name argument can be used only once."
@@ -1439,8 +1440,8 @@ msgstr "terminal inconnu. Vous devez appuyer sur <Entr
 
 #~ msgid "the interval length for the cnsti method must be smaller than %d."
 #~ msgstr ""
-#~ "la longueur d'intervalle pour la méthode cnsti doit être plus petite que %"
-#~ "d."
+#~ "la longueur d'intervalle pour la méthode cnsti doit être plus petite que "
+#~ "%d."
 
 #~ msgid ""
 #~ "the mask saved in the stego header is not the default (1). This is no "
diff --git a/po/ro.po b/po/ro.po
index f8a08bb..1cc8cb8 100644
--- a/po/ro.po
+++ b/po/ro.po
@@ -9,6 +9,7 @@ msgstr ""
 "PO-Revision-Date: 2003-10-11 09:31+2\n"
 "Last-Translator: TRIMBITAS SORIN <lacroix-iv(NO SPAM)@go.ro>\n"
 "Language-Team: ROMANIAN <lacroix-iv(NO SPAM)@go.ro>\n"
+"Language: \n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=ISO-8859-1\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -89,8 +90,8 @@ msgstr ""
 msgid ""
 "the argument \"%s\" can only be used with the \"%s\" and \"%s\" commands."
 msgstr ""
-"argumentul \"%s\" poate fi folosit doar cu comanda \"%s\" si cu comanda \"%s"
-"\"."
+"argumentul \"%s\" poate fi folosit doar cu comanda \"%s\" si cu comanda "
+"\"%s\"."
 
 #: src/Arguments.cc:306
 #, c-format
@@ -535,8 +536,8 @@ msgstr "terminare prematura a datelor bmp de la intrarea standard."
 #, c-format
 msgid "an error occured while writing the bitmap data to the file \"%s\"."
 msgstr ""
-"o eroare a fost generata in timpul scrierii datelor bitmap in fisierul \"%s"
-"\"."
+"o eroare a fost generata in timpul scrierii datelor bitmap in fisierul "
+"\"%s\"."
 
 #: src/BmpFile.cc:844
 msgid "an error occured while writing the bitmap data to standard output."
@@ -972,8 +973,8 @@ msgstr "nu am putut seta atributele terminalului."
 #, c-format
 msgid "an error occured while reading the wav headers from the file \"%s\"."
 msgstr ""
-"o eroare a fost generata in timp ce se citeau header-ele wav din fisierul \"%"
-"s\"."
+"o eroare a fost generata in timp ce se citeau header-ele wav din fisierul "
+"\"%s\"."
 
 #: src/WavFile.cc:352
 #, c-format
@@ -1009,16 +1010,16 @@ msgid ""
 "the wav file from standard input has a format that is not supported "
 "(FormatTag: 0x%X)."
 msgstr ""
-"fisierul WAV de la intrarea standard este intr-un format care nu e suportat"
-"(FormatTag: 0x%X)."
+"fisierul WAV de la intrarea standard este intr-un format care nu e "
+"suportat(FormatTag: 0x%X)."
 
 #: src/WavFormatChunk.cc:34
 #, c-format
 msgid ""
 "the wav file \"%s\" has a format that is not supported (FormatTag: 0x%X)."
 msgstr ""
-"fisierul WAV \"%s\" este intr-un format care nu este suportat (FormatTag: 0x%"
-"X)."
+"fisierul WAV \"%s\" este intr-un format care nu este suportat (FormatTag: "
+"0x%X)."
 
 #: src/WavFormatChunk.cc:49
 msgid ""
diff --git a/src/Arguments.h b/src/Arguments.h
index 018326c..1f907a7 100644
--- a/src/Arguments.h
+++ b/src/Arguments.h
@@ -100,7 +100,7 @@ class Arguments {
 	static const VERBOSITY	Default_Verbosity = NORMAL ;
 	static const unsigned long	Default_Radius = 0 ; // there is no default radius for all file formats
 	static const unsigned int	Max_Algorithm = 3 ;
-	static const float		Default_Goal = 100.0 ;
+	static constexpr float		Default_Goal = 100.0 ;
 	static const DEBUGCOMMAND	Default_DebugCommand = NONE ;
 	static const bool		Default_Check = false ;
 	static const unsigned int	Default_DebugLevel = 0 ;
diff --git a/src/AuData.h b/src/AuData.h
index b4ccc9a..d287c5a 100644
--- a/src/AuData.h
+++ b/src/AuData.h
@@ -26,22 +26,22 @@
 
 // AuMuLawAudioData
 typedef AudioDataImpl<AuMuLaw,BYTE> AuMuLawAudioData ;
-inline BYTE AuMuLawAudioData::readValue (BinaryIO* io) const { return (io->read8()) ; }
-inline void AuMuLawAudioData::writeValue (BinaryIO* io, BYTE v) const { io->write8(v) ; }
+template<> inline BYTE AuMuLawAudioData::readValue (BinaryIO* io) const { return (io->read8()) ; }
+template<> inline void AuMuLawAudioData::writeValue (BinaryIO* io, BYTE v) const { io->write8(v) ; }
 
 // AuPCM8AudioData
 typedef AudioDataImpl<AuPCM8,SBYTE> AuPCM8AudioData ;
-inline SBYTE AuPCM8AudioData::readValue (BinaryIO* io) const { return ((SBYTE) io->read8()) ; }
-inline void AuPCM8AudioData::writeValue (BinaryIO* io, SBYTE v) const { io->write8((BYTE) v) ; }
+template<> inline SBYTE AuPCM8AudioData::readValue (BinaryIO* io) const { return ((SBYTE) io->read8()) ; }
+template<> inline void AuPCM8AudioData::writeValue (BinaryIO* io, SBYTE v) const { io->write8((BYTE) v) ; }
 
 // AuPCM16AudioData
 typedef AudioDataImpl<AuPCM16,SWORD16> AuPCM16AudioData ;
-inline SWORD16 AuPCM16AudioData::readValue (BinaryIO* io) const { return ((SWORD16) io->read16_be()) ; }
-inline void AuPCM16AudioData::writeValue (BinaryIO* io, SWORD16 v) const { io->write16_be((UWORD16) v) ; }
+template<> inline SWORD16 AuPCM16AudioData::readValue (BinaryIO* io) const { return ((SWORD16) io->read16_be()) ; }
+template<> inline void AuPCM16AudioData::writeValue (BinaryIO* io, SWORD16 v) const { io->write16_be((UWORD16) v) ; }
 
 // AuPCM32AudioData
 typedef AudioDataImpl<AuPCM32,SWORD32> AuPCM32AudioData ;
-inline SWORD32 AuPCM32AudioData::readValue (BinaryIO* io) const { return ((SWORD32) io->read32_be()) ; }
-inline void AuPCM32AudioData::writeValue (BinaryIO* io, SWORD32 v) const { io->write32_be((UWORD32) v) ; }
+template<> inline SWORD32 AuPCM32AudioData::readValue (BinaryIO* io) const { return ((SWORD32) io->read32_be()) ; }
+template<> inline void AuPCM32AudioData::writeValue (BinaryIO* io, SWORD32 v) const { io->write32_be((UWORD32) v) ; }
 
 #endif // ndef SH_AUDATA_H
diff --git a/src/AuSampleValues.cc b/src/AuSampleValues.cc
index 64709f3..f5b4ff5 100644
--- a/src/AuSampleValues.cc
+++ b/src/AuSampleValues.cc
@@ -21,17 +21,17 @@
 #include "AuSampleValues.h"
 
 // AuMuLawSampleValue
-const BYTE AuMuLawSampleValue::MinValue = 0 ;
-const BYTE AuMuLawSampleValue::MaxValue = BYTE_MAX ;
+template<> const BYTE AuMuLawSampleValue::MinValue = 0 ;
+template<> const BYTE AuMuLawSampleValue::MaxValue = BYTE_MAX ;
 
 // AuPCM8SampleValue
-const SBYTE AuPCM8SampleValue::MinValue = SBYTE_MIN ;
-const SBYTE AuPCM8SampleValue::MaxValue = SBYTE_MAX ;
+template<> const SBYTE AuPCM8SampleValue::MinValue = SBYTE_MIN ;
+template<> const SBYTE AuPCM8SampleValue::MaxValue = SBYTE_MAX ;
 
 // AuPCM16SampleValue
-const SWORD16 AuPCM16SampleValue::MinValue = SWORD16_MIN ;
-const SWORD16 AuPCM16SampleValue::MaxValue = SWORD16_MAX ;
+template<> const SWORD16 AuPCM16SampleValue::MinValue = SWORD16_MIN ;
+template<> const SWORD16 AuPCM16SampleValue::MaxValue = SWORD16_MAX ;
 
 // AuPCM32SampleValue
-const SWORD32 AuPCM32SampleValue::MinValue = SWORD32_MIN ;
-const SWORD32 AuPCM32SampleValue::MaxValue = SWORD32_MAX ;
+template<> const SWORD32 AuPCM32SampleValue::MinValue = SWORD32_MIN ;
+template<> const SWORD32 AuPCM32SampleValue::MaxValue = SWORD32_MAX ;
diff --git a/src/Graph.cc b/src/Graph.cc
index 4373127..61be241 100644
--- a/src/Graph.cc
+++ b/src/Graph.cc
@@ -18,6 +18,7 @@
  *
  */
 
+#include <climits>
 #include <ctime>
 #include <list>
 #include <map>
diff --git a/src/MHashPP.cc b/src/MHashPP.cc
index 27b3d73..fac6c4b 100755
--- a/src/MHashPP.cc
+++ b/src/MHashPP.cc
@@ -120,7 +120,7 @@ std::string MHashPP::getAlgorithmName ()
 
 std::string MHashPP::getAlgorithmName (hashid id)
 {
-	char *name = mhash_get_hash_name (id) ;
+	char *name = (char*)mhash_get_hash_name (id) ;
 	std::string retval ;
 	if (name == NULL) {
 		retval = std::string ("<algorithm not found>") ;
diff --git a/src/ProgressOutput.h b/src/ProgressOutput.h
index 3a235a3..394939f 100644
--- a/src/ProgressOutput.h
+++ b/src/ProgressOutput.h
@@ -64,7 +64,7 @@ class ProgressOutput {
 	 **/
 	void done (float rate, float avgweight = NoAvgWeight) const ;
 
-	static const float NoAvgWeight = -1.0 ;
+	static constexpr float NoAvgWeight = -1.0 ;
 
 	protected:
 	std::string vcompose (const char *msgfmt, va_list ap) const ;
`

**Comment by nick863** [comment]
Potential caveat: the new code may not work on old versions of compilers, but I C++98 is not a default option for a long time.

**Comment by FalcoGer** [comment]
@nick863 could you triple backtick quote that for easier copying? as it is now, markdown makes a mess of it.

**Comment by nick863** [comment]
Fixed, I am sorry, I did not noticed earlier.

**Comment by Panagiss** [comment]
Any news about this?
I'm still experiencing the problem

**Comment by nick863** [comment]
I think, the fix has been merge in the [commit](https://github.com/btlorch/steghide/commit/3a3f67fb0651a1106dff7c40a2fe57d65b63084b). @Panagiss, do you see the same error after syncing with master?

**Comment by Panagiss** [comment]
Yes, I still experience the issue

```
Arguments.h:103:41: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float Arguments::Default_Goal’ of non-integral type [-fpermissive]
  103 |         static const float              Default_Goal = 100.0 ;
```

I'm not sure if the commit you showed be was merged

**Comment by nick863** [comment]
That is strange, could you please check if you have the latest version of code? In the latest master it says the commit has merged:
![изображение](https://github.com/StefanoDeVuono/steghide/assets/30440255/95ca5df8-d66a-4a01-a7b5-2e6238755600)
so it already should have `constexpr` instead of `const`.
What `git status` shows for you?

**Comment by StefanoDeVuono** [comment]
Hello @FalcoGer, @telometto, @Osiris9999 @Aminuxer, @nick863, @FalcoGer. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks!
